[package]
name = "rustris"
version = "0.1.0"
authors = ["Abderrahmane TAHRI JOUTI <tj.abderrahmane@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.7"
mint = "0.5"
nalgebra = "0.18"
structopt = "0.2"
glam = { version = "0.15.2", features = ["mint"] }
rand = "0.7"
