[package]
name = "rustris"
version = "0.2.0"
authors = ["Abderrahmane TAHRI JOUTI <tj.abderrahmane@gmail.com>"]
edition = "2021"

[dependencies]

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["gfx"]
